<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mTestMetamodel1" nsURI="http://www.example.org/mTestMetamodel1"
    nsPrefix="mTestMetamodel1">
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass3" eType="#//NewEClass3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass2"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass3" eSuperTypes="#//NewEClass2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass13" lowerBound="1"
        eType="ecore:EClass ../../mtest.metamodel3/model/metamodel3.ecore#//NewEClass13"/>
  </eClassifiers>
</ecore:EPackage>
